### ISSUE TITLE
HostnameToIpResolver.ResolveToIpv4Async throws different exceptions on different platforms

### ISSUE THREAD

**Issue by pingvinen** [rapidcore/issues#8]
The method should catch the exception from the DNS-stack and wrap it in another exception, so we always know what kind of exception can be thrown - regardless of platform.

Currently this is shown by the unit test if run on Linux or Mac.

From Linux:
```
Failed   RapidCore.UnitTests.Network.HostnameToIpResolverTest.HostnameToIpResolve_can_fail
Error Message:
 Assert.Throws() Failure
Expected: typeof(System.Net.Sockets.SocketException)
Actual:   typeof(System.Net.Internals.SocketExceptionFactory+ExtendedSocketException): No such device or address
Stack Trace:
   at System.Net.Dns.HostResolutionEndHelper(IAsyncResult asyncResult)
   at System.Net.Dns.EndGetHostAddresses(IAsyncResult asyncResult)
   at System.Net.Dns.<>c.<GetHostAddressesAsync>b__14_1(IAsyncResult asyncResult)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at RapidCore.Network.HostnameToIpResolver.<ResolveToIpv4Async>d__0.MoveNext() in /home/patrick/workspace/rapidcore/rapidcore/src/Network/HostnameToIpResolver.cs:line 18
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at RapidCore.UnitTests.Network.HostnameToIpResolverTest.<>c__DisplayClass1_0.<<HostnameToIpResolve_can_fail>b__0>d.MoveNext() in /home/patrick/workspace/rapidcore/rapidcore/test/unit/Network/HostnameToIpResolverTest.cs:line 23
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
```

**Comment by nover** [comment]
You can actually catch the `SocketException` on nix variants, it was just the test case that was being too strict and non-cross-platform compatible.

once we get PR https://github.com/rapidcore/rapidcore/pull/16 merged things like these should not happen again :)
